[project]
name = "calculator"
version = "0.1.0"
description = "A simple calculator for CI demo"
requires-python = ">=3.12"
dependencies = [
    "pytest",
    "flake8"
]

[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["tests"]